### ISSUE TITLE
Collection of candidate rules

### ISSUE THREAD

**Issue by crispgm** [UrlAutoRedirector/UrlAutoRedirector#17]
As UrlAutoRedirector is a tools to getting more convenience in surf the Internet, we need some useful rules/presets to make it more powerful and awesome.

Here we start a collection thread to get useful rules. And non-redundant rules will be add to preset rules list by default in the next release.

Cheers.

**Comment by crispgm** [comment]
the current applications are listed here,

* 京东中间页
* 大众点评移动转PC
* 微博移动转PC
* Baidu to Google(troll?)

any candidates? @lzb

**Comment by lzb** [comment]
ai.taobao.com/xxx -?
mobile taobao to PC?

**Comment by crispgm** [comment]
@lzb any examples?

**Comment by crispgm** [comment]
New rules of QQ Sports

# Example
src: [http://xw.qq.com/sports/20160708047779/SPO2016070804777909](http://xw.qq.com/sports/20160708047779/SPO2016070804777909)
dst: [http://sports.qq.com/a/20160708/047779.htm](http://sports.qq.com/a/20160708/047779.htm)

# Rule
src: ^http://xw.qq.com/sports/(\d{8})(\d{6})/(.*)$
dst: http://sports.qq.com/a/$1/$2.htm
regex: true

**Comment by crispgm** [comment]
## Shuoke of autohome

### Description

Redirect from mobile page to PC's Shuoke of autohome

### Example

src: http://m.autohome.com.cn/shuoke/530751.html
dst: http://shuoke.autohome.com.cn/article/530751.html

### Rule

src: `^http://m.autohome.com.cn/shuoke/(\d).html
dst: `http://shuoke.autohome.com.cn/article/$1.html`
regex: `true`

**Comment by crispgm** [comment]
src: `http://m.ziroom.com/BJ/room/130399.html`
dst: `http://www.ziroom.com/z/vr/130399.html`
regex: `true`

**Comment by crispgm** [comment]
src: `http://m.csdn.net/article/2012-07-05/2807113-less-is-exponentially-more`
dst: `http://www.csdn.net/article/2012-07-05/2807113-less-is-exponentially-more`

**Comment by crispgm** [comment]
src: `http://m.afwing.com/encyclopaedia/the-turbinlite-havoc.html`
dst: `http://www.afwing.com/encyclopaedia/the-turbinlite-havoc.html`

**Comment by crispgm** [comment]
src: `https://m.douban.com/note/588714829/?dt_dapp=1`
dst: `https://www.douban.com/note/588714829/?dt_dapp=1`

**Comment by holykanolie** [comment]
Source: `^https://ad.doubleclick.net/ddm/clk/(.*);o?(.*)http://(.*)`
Destination: `http://$3`

Works, feel free to add to your rules distro

**Comment by xPsyBit** [comment]
Source: `^https://open.spotify.com/track/(.*)`
Source: `^open.spotify.com/track/(.*)`
Destination: `https://songlink.io/https://open.spotify.com/track/$1`

Adding other streaming services as the source would be pretty nice too

**Comment by ekikoshin** [comment]
After the update, the plug-in option must be turned on first and then switched on again before it can be used
