### ISSUE TITLE
Features collecting thread

### ISSUE THREAD

**Issue by crispgm** [UrlAutoRedirector/UrlAutoRedirector#19]
If you have any ideas about this extension, please write it here.

**Comment by crispgm** [comment]
An idea: use UAR as Alfred

**Comment by doumaomao** [comment]
add the availability detection of  the target link

**Comment by crispgm** [comment]
Is it okay to put a PayPal/Alipay/ApplePay donation qr? @lzb

**Comment by crispgm** [comment]
- [ ] Use webRequest instead
- [ ] Make "Prompt mark" configurable
