### ISSUE TITLE
optimize the option page/ rules section

### ISSUE THREAD

**Issue by lzb** [UrlAutoRedirector/UrlAutoRedirector#36]
- [ ] I believe this to be a bug, not a question about using URL Auto Redirector.
- [ ] This is a feature request.

---

## My OS

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

## My Chrome Version

---

- [ ] I cannot install URL Auto Redirector.
- [ ] The rules do not work.

**Comment by crispgm** [comment]
Planned in 1.2.0 #39 
New interaction design will be set this weekend.
