### ISSUE TITLE
use font-family: sans for Chinese version of browser

### ISSUE THREAD

**Issue by lzb** [UrlAutoRedirector/UrlAutoRedirector#38]
- [x] I believe this to be a bug, not a question about using URL Auto Redirector.
- [ ] This is a feature request.

---

## My OS

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

## My Chrome Version

---

- [ ] I cannot install URL Auto Redirector.
- [ ] The rules do not work.

**Comment by lzb** [comment]
Currently it shows 宋体+Arial in Chinese version of Chrome, which is not perfect.
![Uploading image.png…]()

**Comment by crispgm** [comment]
It is a bug, because Chinese font has not been considered yet.
Any candidates? I prefer Open Sans. @lzb

**Comment by lzb** [comment]
open sans is ok. are you embedding it? on windows i would recommend 雅黑 as fail safe.

**Comment by crispgm** [comment]
@lzb should be embedded for Open Sans, and it will not be any failure theoretically.

**Comment by lzb** [comment]
sure. that's it for now.
