### ISSUE TITLE
Not loaded: please delete twitter button dependence

### ISSUE THREAD

**Issue by zetopowef** [URLAutoRedirector/URLAutoRedirector#66]
- [ ] This is a feature request.

---

## My OS

- [ ] I am on (or have tested on) ***Windows*** 10+

## My Chrome Version 60

---

## My Reproduction Steps

Some necessary chrome rules dont give ability to load internals like your button on/off from twitter
Please make all built-in plugin

**Comment by crispgm** [comment]
I am not clear that whether the problem is that the Twitter Share button blocks the on/off button?

The on/off has no external dependencies. We only depend Twitter for the sharing button.
