### ISSUE TITLE
Whenever the extension auto-updates itself, new rules will override user defined rules, potentially causing data loss unless the user has exported their rules before

### ISSUE THREAD

**Issue by Kevin-He-DVHS** [URLAutoRedirector/URLAutoRedirector#68]
- [x] I believe this to be a bug, not a question about using URL Auto Redirector.
- [ ] This is a feature request.

---

## My OS

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

## My Chrome Version
- 72.0.3626.81 (Official Build) (64-bit)
---

- [ ] I cannot install URL Auto Redirector.
- [ ] The rules do not work.

## My Reproduction Steps

1. Add some custom user rules by right-clicking this extension and click options.
2. Click new and add some custom rules
3. Let the extension update itself
4. When new [_awesome rules_](https://github.com/URLAutoRedirector/URLAutoRedirector/issues/17) are added, the extension seems to auto-reset the rules and override the user-defined rules

## Remarks
The issue should be very hard to reproduce because updates rarely occur, but I appreciate the development's team's effort to investigate this issue. While it may be a feature request to add the ability to not subscribe to [The Collection of Awesome Rules](https://github.com/URLAutoRedirector/URLAutoRedirector/issues/17). I personally never found useful to included those rules and mainly use my own rules. But it now seems that this extension's main focus is on awesome rules rather than build the extension as an advanced customizer.

**Comment by crispgm** [comment]
Thanks for the report.

Actually it's not hard to reproduce, since I can reload in dev-mode. It happens when `chrome.runtime.onInstalled` is triggered. I will try my best figure it out recently.

And I want to clarify that it's not a subscription to awesome-rules by design, but it simply always (may not) ship with latest collection of rules.

**Comment by crispgm** [comment]
for me, it basically works on 1.8.0. @Kevin-He-DVHS please backup and try it. 😄

**Comment by Kevin-He-DVHS** [comment]
@crispgm I tried the new version and it works. Thanks for fixing and you can close this issue now.
