### ISSUE TITLE
Redirects continuously, you cannot navigate the page

### ISSUE THREAD

**Issue by gidancatalin** [URLAutoRedirector/URLAutoRedirector#69]
I made the following rule
^https?://www.booking.com(.*)    to   https://www.booking.com/index.html

and site is blocked , its redirects continuously, you cannot navigate the page .I want to redirect only once and then be able to browse the site.
tanks !

**Comment by crispgm** [comment]
@gidancatalin it looks that your RegExp do apply like what you describe. What do you really want by this rule?

**Comment by gidancatalin** [comment]
After applying the rule i want  navigate further on the site.

**Comment by gidancatalin** [comment]
yes

**Comment by gidancatalin** [comment]
If its posible

**Comment by crispgm** [comment]
Looks not possible for this, but it's possible to prevent infinite redirection, which seems have the same effect.

**Comment by gidancatalin** [comment]
Tanks but how i do it?If you cant send me one example

**Comment by crispgm** [comment]
It needs a new feature to support this.

**Comment by gidancatalin** [comment]
To prevent infinite redirection?

**Comment by crispgm** [comment]
@gidancatalin sorry, i investigate on this case. It cannot be solved. Since Booking.com appends a session-id like string to URL and changes every time.

**Comment by gidancatalin** [comment]
Ok ,tanks . I will wait if you cant do this .... tanks again
