### ISSUE TITLE
Rules for CNKI

### ISSUE THREAD

**Issue by MkQtS** [URLAutoRedirector/URLAutoRedirector#71]
# Rules for CNKI

将知网空间、知网国内版等部分页面重定向到知网海外版，便于使用学校IP下载文献PDF

### example 1

src:[http://www.cnki.com.cn/Article/CJFDTOTAL-LSJX201704007.htm](http://www.cnki.com.cn/Article/CJFDTOTAL-LSJX201704007.htm)

dst:[https://chn.oversea.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&filename=LSJX201704007](https://chn.oversea.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&filename=LSJX201704007)

### example 2

src:[http://cpfd.cnki.com.cn/Article/CPFDTOTAL-OGTX201512001026.htm](http://cpfd.cnki.com.cn/Article/CPFDTOTAL-OGTX201512001026.htm)

dst:[https://chn.oversea.cnki.net/kcms/detail/detail.aspx?dbcode=CPFD&filename=OGTX201512001026](https://chn.oversea.cnki.net/kcms/detail/detail.aspx?dbcode=CPFD&filename=OGTX201512001026)

#### bug:[`(?i)`doesn't work] Win10 & Chrome 89

src:`^https?:\/\/(cpfd|www)\.cnki\.com\.cn\/Article\/([A-Z]{4})((?i)total)-(\w+)\.htm.*$`

dst:`https://chn.oversea.cnki.net/kcms/detail/detail.aspx?dbcode=$2&filename=$4`

### example

src: [http://cdmd.cnki.com.cn/Article/CDMD-80133-1015953531.htm](http://cdmd.cnki.com.cn/Article/CDMD-80133-1015953531.htm)

dst: [https://chn.oversea.cnki.net/kcms/detail/detail.aspx?dbcode=CDMD&filename=1015953531.nh](https://chn.oversea.cnki.net/kcms/detail/detail.aspx?dbcode=CDMD&filename=1015953531.nh)

### rule

src: `^https?:\/\/cdmd\.cnki\.com\.cn\/Article\/([A-Z]{4})-\d+-(\d+)\.htm.*$`

dst: `https://chn.oversea.cnki.net/kcms/detail/detail.aspx?dbcode=$1&filename=$2.nh`

### example

src:[https://kns.cnki.net/kcMs/detail/detail.aspx?dbcode=CAPJ&dbname=CAPJDAY&filename=JLGY20210331003&v=%25mmd2BtjQTGKS2M63pmspvHEWp5D3GsrarDu1KgKeIUJT6U%25mmd2F27WT8nsatAPXxeCqe4QUU](https://kns.cnki.net/kcMs/detail/detail.aspx?dbcode=CAPJ&dbname=CAPJDAY&filename=JLGY20210331003&v=%25mmd2BtjQTGKS2M63pmspvHEWp5D3GsrarDu1KgKeIUJT6U%25mmd2F27WT8nsatAPXxeCqe4QUU)

dst:[https://chn.oversea.cnki.net/kcMs/detail/detail.aspx?dbcode=CAPJ&filename=JLGY20210331003](https://chn.oversea.cnki.net/kcMs/detail/detail.aspx?dbcode=CAPJ&filename=JLGY20210331003)

### rule

src:`^https?:\/\/\S*\.cnki\.net\/((?i)kcms)\/detail\/detail\.aspx\?(?=.*dbcode\=(\w+))(?=.*filename\=([\w\.]+)).*$`

dst:`https://chn.oversea.cnki.net/kcms/detail/detail.aspx?dbcode=$2&filename=$3`

**Comment by crispgm** [comment]
`?i`这块就是JavaScript的RegExp，看看是不是不支持，其它的没问题，可以添加到非默认enabled的规则中。
