### ISSUE TITLE
Chrome/Edge sync

### ISSUE THREAD

**Issue by kaovilai** [URLAutoRedirector/URLAutoRedirector#74]
- [x] This is a feature request.

---
I would like to see this extension implement Chrome sync via storage.sync mentioned on https://developer.chrome.com/docs/extensions/reference/storage/

**Comment by kaovilai** [comment]
Here's an example
https://github.com/gorhill/uBlock/blob/c4b7ee80ea7b22d1f870f9a0e09be9de225cf0b3/platform/chromium/webext.js#L143

**Comment by crispgm** [comment]
Thanks for the idea. I am trying figure that out. The migration to sync is easy but I need to load from local at first and then to sync.

**Comment by crispgm** [comment]
The v1.13.0 release will include this feature. Please update and enjoy. Thank you very much for the suggestion.
