### ISSUE TITLE
Question Very Simple redirection is not working 

### ISSUE THREAD

**Issue by mailsanchu** [URLAutoRedirector/URLAutoRedirector#76]
My rule is very simple 
http://localhost:9000(.*) to https://abc.net$1

And my URL is 
http://localhost:9000/project/issues

But it is not detecting and redirect. Can you please help

**Comment by mailsanchu** [comment]
Looks like localhost is not working. There is no server running on localhost 9000. Please see the attached image

![image](https://user-images.githubusercontent.com/32928538/171654506-751caf0e-2ebb-441b-abcc-def6a851107d.png)

**Comment by crispgm** [comment]
> Looks like localhost is not working. There is no server running on localhost 9000. Please see the attached image
> 
> ![image](https://user-images.githubusercontent.com/32928538/171654506-751caf0e-2ebb-441b-abcc-def6a851107d.png)

I don't the exact reason. But I basically have an idea for this.

First, URL that cannot be loaded is also available when Chrome really tries to load that. However, after failing to load, Chrome will not actually even try (kinda like a cache) so that the extension will not capture the loading event to trigger the redirection.

**Comment by mailsanchu** [comment]
I used to another URL redirector extension and that used to work for the above scenario. But for some reason that extension is removed from chromestore

**Comment by mailsanchu** [comment]
Yeah that sounds right to me. I can see the **from** URL for a second then it redirects with this extension. Older one I did not see that behaviour

**Comment by crispgm** [comment]
> Yeah that sounds right to me. I can see the **from** URL for a second then it redirects with this extension. Older one I did not see that behaviour

I read that doc again and now I think I can figure this out later.

**Comment by mailsanchu** [comment]
:) I tested the above scenario and it worked perfectly. I will test more on Tuesday

**Comment by mailsanchu** [comment]
This is the old extension I was talking about https://extpose.com/ext/118821

**Comment by mailsanchu** [comment]
It has a nice test panel to test the rules and I think that is a nice addon to this extension

**Comment by crispgm** [comment]
Since it works not bad, I plan to publish today or tomorrow.

**Comment by mailsanchu** [comment]
Seeing sometimes the service worker is inactive and nothing works during that time 
![image](https://user-images.githubusercontent.com/32928538/172015632-c22264de-d871-4d95-a0e1-80b86e88e588.png)

**Comment by crispgm** [comment]
> Seeing sometimes the service worker is inactive and nothing works during that time ![image](https://user-images.githubusercontent.com/32928538/172015632-c22264de-d871-4d95-a0e1-80b86e88e588.png)

I think this is mananaged by Chrome to save battery cost or something else. When you click 'inactive', it will be reactivated.

**Comment by crispgm** [comment]
The `1.14.0` version has been submitted for preview and will be release ASAP it's reviewed.

**Comment by mailsanchu** [comment]
Hi there, Keep up the good work. Thank you for considering my request. 
A small token of appreciation, I just got a cup of tea

**Comment by crispgm** [comment]
> Hi there, Keep up the good work. Thank you for considering my request.
> A small token of appreciation, I just got a cup of tea

Thank you very much ❤️

**Comment by crispgm** [comment]
There are actually some bug reports for the "Service worker (inactive) issues. I have submitted a hot fix version to add workaround for this today.

**Comment by mailsanchu** [comment]
I tried the latest but service worker still goes into inactive state

**Comment by crispgm** [comment]
> I tried the latest but service worker still goes into inactive state

OMG. I am thinking of reverting it back.

**Comment by mailsanchu** [comment]
It has no effect on me.Look out for other users
