### ISSUE TITLE
Url Auto Redirector works only intermittently 

### ISSUE THREAD

**Issue by Birdieeagle** [URLAutoRedirector/URLAutoRedirector#79]
Hi,
I've been using this chrome extension for a few months and it has been working fine till recent times.

I like this extension because it loops as I use it to keep trying a closed Google form until it opens. Other redirector extensions doesn't loop and it seems only this one does.

Here's what I want to do:
Redirect
https://docs.google.com/1FaP..../closedform 
to
https://docs.google.com/1FaP..../viewform

Recently, it doesn't seem to loop 100% of the time. It fails about half the time and returns me the closed google form. Has it got anything to do with new version release?

Appreciate any help to solve this issue.  Thanks.

**Comment by crispgm** [comment]
@Birdieeagle sorry to cause the trouble. There is an issue with service worker of Chrome extension, I am trying to figure out a workaround for that. Otherwise, I will switch back to a former version's codes. Please wait for the update today.

**Comment by crispgm** [comment]
> Thank you for the quick response. Is there an update?

Yes please update to the v1.17.0

**Comment by Birdieeagle** [comment]
Hi, I've don't see any update button to update.  Anyway, I removed from Chrome and added the extension again to ensure it is very 1.17.0.

However, it still doesn't loop.  In fact it never loops now, which is worse than intermittent. Any idea what I did wrongly?  I'm still trying to loop a closed Google form to a viewform. I'm doing this to automate clicking viewform until google form opens at a specific time. 

Redirect
https://docs.google.com/1FaP..../closedform
to
https://docs.google.com/1FaP..../viewform

Any idea where I have gone wrong?  Can I use the version that I used back in Mar 2022?

Thank you.

**Comment by crispgm** [comment]
> Hi, I've don't see any update button to update. Anyway, I removed from Chrome and added the extension again to ensure it is very 1.17.0.
> 
> However, it still doesn't loop. In fact it never loops now, which is worse than intermittent. Any idea what I did wrongly? I'm still trying to loop a closed Google form to a viewform. I'm doing this to automate clicking viewform until google form opens at a specific time.
> 
> Redirect https://docs.google.com/1FaP..../closedform to https://docs.google.com/1FaP..../viewform
> 
> Any idea where I have gone wrong? Can I use the version that I used back in Mar 2022?
> 
> Thank you.

You may please have a check on the rule. Is that gone away or something else?
I reverted back to code before and also added up something new.

If you'd like use an earlier version, you may download a zip here though.

**Comment by Birdieeagle** [comment]
Thanks. I'm not sure where to get the "zip here".
Also, just to be clear, the redirect from Google Form Closed to Google Form Open works. Just that it now doesn't continuously loop from closed to open to closed to open ....until the time when the Google form opens.  Now it just stays at closed.

Hope I'm making myself clear.  

Do advise where to get the zip file as I'm new to Github.

A thousand thanks.

**Comment by crispgm** [comment]
[UrlAutoRedirector-1.12.0.zip](https://github.com/URLAutoRedirector/URLAutoRedirector/files/8954266/UrlAutoRedirector-1.12.0.zip)
@Birdieeagle since you are not familiar with this, you may just download here.

**Comment by Birdieeagle** [comment]
Thank you so much. Managed to load this version manually into my chrome. Now it works like it used to and loops the closedform to viewform till it opens at the specified time. Thanks again.
