### ISSUE TITLE
https://www.westernjournal.com/ is blocking extension

### ISSUE THREAD

**Issue by fatkdog** [URLAutoRedirector/URLAutoRedirector#83]
- [x] I believe this to be a bug, not a question about using URL Auto Redirector.
- [ ] This is a feature request.

---

## My OS

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

## My Chrome Version
Version 106.0.5249.119 (Official Build) (x86_64)
---

- [ ] I cannot install URL Auto Redirector.
- [ ] The rules do not work.

## My Reproduction Steps
If I make any simple rule for the website:
**https://www.westernjournal.com/**
it doesn't work
_The website seems to be blocking redirection_
If I make the exact same rule for another domain the rule works fine.

1. Step 1
2. Step 2
3. Step 3

Thanks for looking into it!
-k

**Comment by crispgm** [comment]
Please show one of your simple rules so that I can reproduce the issue.

**Comment by fatkdog** [comment]
Hi, thanks for the response. Appreciate you looking into this.
## Is Website Blocking URL Redirection?

|Rule|Source|Destination|RegExp|
|:-:|:-|:-|:-:|
|1|http(s)?://((www\\.)?westernjournal\\.com.\*)\\?utm.\*|https://$1|yes|
|2|(http(s)?://)([^?]\*)\\?[um]tm_.*|$1$3|yes|
|3|https://www\.westernjournal\.com.*|https://www.google.com|yes|

Tested with the following URL:\
https://www.westernjournal.com/lapd-detective-gives-spine-chilling-5-word-warning-americans/?utm_source=email&utm_medium=AE&utm_campaign=can&utm_content=2022-10-30&seyid=12345

Rule 1: I have replaced "westernjournal" with other urls and it works.\
Rule 2: Was just for testing, it removes a "?" and any junk after it, if it also is "?utm_" OR "?mtm_". It works for any url that has "?utm_" EXCEPT westernjournal urls
Rule 3: I would never use, I just used it to verify that it was unique to westernjournal, when I replace westernjournal in rule 3 with some other url it works to redirect to google

**Comment by crispgm** [comment]
> Rule 1

I have no idea with complicated RegExp but this works fine for me:
`https?:\/\/((www.)?westernjournal.com\/(.*)\/)\?utm.*` -> `https://$1`. See also <https://regex101.com/r/jZ7nE3/1>

> Rule 3

I tried `https://www.westernjournal.com/*`, and it works well.

**Comment by fatkdog** [comment]
Huh, it's working, I musta missed something.
Might have been a chrome update I needed to install?
I hadn't restarted chrome in about 3 weeks...

Appreciate the time.
Thx for the link to that regex site.
Some good info there.
