### ISSUE TITLE
重定向会跳转或者打开两次，如果设置为在新的标签页中跳转，则会打开两个新网页。

### ISSUE THREAD

**Issue by ylimys** [URLAutoRedirector/URLAutoRedirector#84]
1.17.1版本

**Comment by crispgm** [comment]
@ylimys 方便提供下规则和测试URL？

**Comment by ylimys** [comment]
![image](https://user-images.githubusercontent.com/20252583/206086774-848a770e-071b-4e03-a58a-11c2bbf3eae8.png)
![image](https://user-images.githubusercontent.com/20252583/206086858-d37ff679-b079-4cac-b828-7f8aedec47b7.png)
新标签打开，用的就是自带的最后那个百度转谷歌，新标签打开两个谷歌，通配符正则都一样，试了一下新建其他规则也一样，我刚装的win11，最新的Chrome，我记得之前不会的，这不能是电脑问题吧，路由器也没弄啥呀。
我换了台电脑试了下，还是一样的，跳转会打开两个。

**Comment by ylimys** [comment]
感谢回复，如果你那边试着没有问题就算了，那就可能是我的问题，我自己研究下。
![image](https://user-images.githubusercontent.com/20252583/206087400-3f8f7213-9780-4637-a4c5-3acf2847f679.png)

**Comment by crispgm** [comment]
我这边也会有这个问题 感谢提报

**Comment by crispgm** [comment]
最新的版本应该修复了 可以升级体验下
